spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql:${DB_HOST_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # API configurations for production environment
  api:
    viacep:
      base-url: ${VIACEP_BASE_URL_PROD:https://viacep.com.br}