spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_HOST_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # API configurations for development environment
  
  # Configurações do Apache Kafka para desenvolvimento
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_DEV:kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID_DEV:hex-group-dev}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        enable.auto.commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

api.viacep.base-url: ${VIACEP_BASE_URL_DEV:https://viacep.com.br}

# Tópicos do Kafka para desenvolvimento
kafka:
  topics:
    person-created: ${KAFKA_TOPIC_PERSON_CREATED_DEV:person-created-dev}
