spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  servlet:
    context-path: /hex/api
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
      file-size-threshold: 0
      location: ~/temp/

springdoc:
  swagger-ui:
    path: /public/swagger

  # Configurações personalizadas da aplicação
  app:
  logging:
    include-context-details: true
    max-response-size-in-log: 1000
    include-full-stack-trace: false
  cache:
    default-time-to-live-seconds: 300
    max-size: 1000
  monitoring:
    slow-execution-threshold-ms: 1000
    log-slow-methods: true